/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.DAO.VerificaLoginDAO;
/**
 *
 * @author PDaniel
 */
public class MenuGerentes extends javax.swing.JFrame {

    /**
     * Creates new form MenuGerentes
     */
    public MenuGerentes() {
        initComponents();
    }
    public void PClose(){
        this.dispose();
        //DO_NOTHING_ON_CLOSE, HIDE_ON_CLOSE, DISPOSE_ON_CLOSE, or EXIT_ON_CLOSE
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastroFuncionarios1 = new javax.swing.JButton();
        CadastroProdutos1 = new javax.swing.JButton();
        RelatoriosGerais1 = new javax.swing.JButton();
        CadastroFuncionarios2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        CadastroFuncionarios1.setText("Gerenciamento de Gerentes");
        CadastroFuncionarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroFuncionarios1ActionPerformed(evt);
            }
        });

        CadastroProdutos1.setText("Gerenciamento de Produtos");
        CadastroProdutos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroProdutos1ActionPerformed(evt);
            }
        });

        RelatoriosGerais1.setText("Relatorios Gerais");

        CadastroFuncionarios2.setText("Gerenciamento de Clientes");
        CadastroFuncionarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroFuncionarios2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Menu Gerente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CadastroProdutos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RelatoriosGerais1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CadastroFuncionarios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CadastroFuncionarios2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(113, 113, 113))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(CadastroFuncionarios2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CadastroFuncionarios1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CadastroProdutos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RelatoriosGerais1)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroFuncionarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroFuncionarios1ActionPerformed
        // TODO add your handling code here:

        if(VerificaLoginDAO.LoginConfirm==1){

            CRUDGerentes telaCRUD = new CRUDGerentes();
            telaCRUD.setVisible(true);//Fun�ao padrao para ativar a tela
        }
        else{
            ViewLogins viewLogin = new ViewLogins();
            viewLogin.setVisible(true);//Fun�ao padrao para ativar a tela
        }

    }//GEN-LAST:event_CadastroFuncionarios1ActionPerformed

    private void CadastroProdutos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroProdutos1ActionPerformed

        if(VerificaLoginDAO.LoginConfirm==1){

            CRUDProdutos telaProdutos = new CRUDProdutos();
            telaProdutos.setVisible(true);//Fun�ao padrao para ativar a tela
        }
        else{
            ViewLogins viewLogin = new ViewLogins();
            viewLogin.setVisible(true);//Fun�ao padrao para ativar a tela
        }

    }//GEN-LAST:event_CadastroProdutos1ActionPerformed

    private void CadastroFuncionarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroFuncionarios2ActionPerformed
        // TODO add your handling code here:
        if(VerificaLoginDAO.LoginConfirm==1){

            CRUDCliente telaCRUDClientes = new CRUDCliente();
            telaCRUDClientes.setVisible(true);//Fun�ao padrao para ativar a tela
        }
        else{
            ViewLogins viewLogin = new ViewLogins();
            viewLogin.setVisible(true);//Fun�ao padrao para ativar a tela
        }
    }//GEN-LAST:event_CadastroFuncionarios2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new MenuGerentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroFuncionarios1;
    private javax.swing.JButton CadastroFuncionarios2;
    private javax.swing.JButton CadastroProdutos1;
    private javax.swing.JButton RelatoriosGerais1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
